export const GET_ACHIEVEMENTS_REQUEST = "GET_ACHIEVEMENTS_REQUEST";
export const GET_ACHIEVEMENTS_SUCCESS = "GET_ACHIEVEMENTS_SUCCESS";

export const ADD_NEW_ACHIEVEMENT_REQUEST = "ADD_NEW_ACHIEVEMENT_REQUEST";
export const ADD_NEW_ACHIEVEMENT_SUCCESS = "ADD_NEW_ACHIEVEMENT_SUCCESS";
export const ADD_NEW_ACHIEVEMENT_FAILURE = "ADD_NEW_ACHIEVEMENT_FAILURE";

export const UPDATE_ACHIEVEMENT_REQUEST = "UPDATE_ACHIEVEMENT_REQUEST";
export const UPDATE_ACHIEVEMENT_SUCCESS = "UPDATE_ACHIEVEMENT_SUCCESS";

export const DELETE_ACHIEVEMENT_REQUEST = "DELETE_ACHIEVEMENT_REQUEST";
export const DELETE_ACHIEVEMENT_SUCCESS = "DELETE_ACHIEVEMENT_SUCCESS";

export const IS_ADD_ACHIEVEMENT_SUCCESS_TO_FALSE = "IS_ADD_ACHIEVEMENT_SUCCESS_TO_FALSE"
export const IS_IPDATE_ACHIEVEMENT_SUCCESS_TO_FALSE = "IS_IPDATE_ACHIEVEMENT_SUCCESS_TO_FALSE"

export const UPLOADING_ACHIEVEMENT_IMAGE_REQUEST = "UPLOADING_ACHIEVEMENT_IMAGE_REQUEST"
export const UPLOADING_ACHIEVEMENT_IMAGE_SUCCESS = "UPLOADING_ACHIEVEMENT_IMAGE_SUCCESS"