export const GET_REVIEWS_REQUEST = "GET_REVIEWS_REQUEST";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";

export const ADD_NEW_REVIEW_REQUEST = "ADD_NEW_REVIEW_REQUEST";
export const ADD_NEW_REVIEW_SUCCESS = "ADD_NEW_REVIEW_SUCCESS";
export const ADD_NEW_REVIEW_FAILURE = "ADD_NEW_REVIEW_FAILURE";

export const UPDATE_REVIEW_REQUEST = "UPDATE_REVIEW_REQUEST";
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";

export const IS_ADD_REVIEW_SUCCESS_TO_FALSE = "IS_ADD_REVIEW_SUCCESS_TO_FALSE"
export const IS_IPDATE_REVIEW_SUCCESS_TO_FALSE = "IS_IPDATE_REVIEW_SUCCESS_TO_FALSE"

export const UPLOADING_REVIEW_IMAGE_REQUEST = "UPLOADING_REVIEW_IMAGE_REQUEST"
export const UPLOADING_REVIEW_IMAGE_SUCCESS = "UPLOADING_REVIEW_IMAGE_SUCCESS"

